#!/bin/bash
#help 	Set the number of readings to hold in each buffer, passing an integer argument
size=1
if [ $# -gt 0 ]; then
	size=$1
fi
payload='{"size":'$size'}'
curl -s -X POST  -d$payload http://localhost:${DEBUG_SERVICE}/fledge/south/debug/buffer|jq
