#!/bin/bash
# Run a Fledge Dispatcher service written in C/C++
if [ "${FLEDGE_ROOT}" = "" ]; then
  FLEDGE_ROOT=/usr/local/fledge
fi

if [ ! -d "${FLEDGE_ROOT}" ]; then
	logger "Fledge home directory missing or incorrectly set environment"
	exit 1
fi

# startup with delay
delay() {
    for ARG in "$@";
      do
        PARAM=$(echo $ARG | cut -f1 -d=)
        if [ $PARAM = '--delay' ]; then
          PARAM_LENGTH=${#PARAM}
          VALUE="${ARG:$PARAM_LENGTH+1}"
          sleep $VALUE
          break
        fi
    done
}

cd "${FLEDGE_ROOT}/services"
delay "$@"
./fledge.services.dispatcher "$@"
