#!/bin/sh

# Run a Fledge north service written in C/C++
if [ "${FLEDGE_ROOT}" = "" ]; then
	FLEDGE_ROOT=/usr/local/fledge
fi

if [ ! -d "${FLEDGE_ROOT}" ]; then
	logger "Fledge home directory missing or incorrectly set environment"
	exit 1
fi

runvalgrind=y
if [ "$VALGRIND_NORTH" != "" ]; then
	for i in "$@"; do
		case $i in
			--name=*)
				name="`echo $i | sed -e s/--name=//`"
				;;
		esac
	done
	services=$(echo $VALGRIND_NORTH | tr ";" "\n")
	for service in $services; do
		if [ "$service" = "$name" ]; then
			runvalgrind=y
		fi
	done
fi

cd "${FLEDGE_ROOT}/services"
if [ "$runvalgrind" = "y" ]; then
	file=/tmp/north.${name}.valgrind.out
	rm -f $file
	valgrind  --leak-check=full --trace-children=yes --show-leak-kinds=all --track-origins=yes --log-file=$file ./fledge.services.north "$@"
else
	./fledge.services.north "$@"
fi

