#!/bin/bash
# Run a Fledge notification service written in C/C++
if [ "${FLEDGE_ROOT}" = "" ]; then
	FLEDGE_ROOT=/usr/local/fledge
fi

if [ ! -d "${FLEDGE_ROOT}" ]; then
	logger "Fledge home directory missing or incorrectly set environment"
	exit 1
fi

cd "${FLEDGE_ROOT}/services"

# startup with delay
for i in "$@";
  do
    PARAM=$(echo $i | cut -f1 -d=)
    if [ $PARAM = '--delay' ]; then
      PARAM_LENGTH=${#PARAM}
      VALUE="${i:$PARAM_LENGTH+1}"
      sleep $VALUE
      #break
    fi
done

./fledge.services.notification "$@"
