#!/bin/bash
# Run a Fledge Storage service written in C/C++

# Get db schema
FLEDGE_VERSION_FILE="${FLEDGE_ROOT}/VERSION"
FLEDGE_SCHEMA=`cat ${FLEDGE_VERSION_FILE} | tr -d ' ' | grep -i "FLEDGE_SCHEMA=" | sed -e 's/\(.*\)=\(.*\)/\2/g'`
# Get storage engine
res=(`${FLEDGE_ROOT}/services/fledge.services.storage --plugin`)
storagePlugin=${res[0]}
managedEngine=${res[1]}
storageExec=""
pluginStartScript=""

if [[ "${FLEDGE_ROOT}" = "" ]]; then
    if [[ ! -x /usr/local/fledge/services/fledge.services.storage ]] && [[ ! -x /usr/local/fledge/services/storage ]]; then
        logger "Unable to find Fledge storage microservice in the default location"
        exit 1
    else
        # Set plugin script
        pluginStartScript=/usr/local/fledge/scripts/plugins/storage/${storagePlugin}.sh
        # Set storage service exec
        if [[ -x /usr/local/fledge/services/fledge.services.storage ]]; then
            export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/fledge/lib
            storageExec=/usr/local/fledge/services/fledge.services.storage
        else
            storageExec=/usr/local/fledge/services/storage
        fi
        logger "Fledge storage microservice in the default location: /usr/local/fledge"
    fi
else
    # Include common logger script code
    . $FLEDGE_ROOT/scripts/common/write_log.sh
    if [[ ! -x ${FLEDGE_ROOT}/services/fledge.services.storage ]] && [[ ! -x ${FLEDGE_ROOT}/services/storage ]]; then
        write_log "" "scripts.services.storage" "err" "Unable to find Fledge storage microservice in ${FLEDGE_ROOT}/services/storage" "logonly" ""
        exit 1
    else
        # Set plugin script
        pluginStartScript=${FLEDGE_ROOT}/scripts/plugins/storage/${storagePlugin}.sh
        # Set storage service exec
        if [[ -x ${FLEDGE_ROOT}/services/fledge.services.storage ]]; then
            export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${FLEDGE_ROOT}/lib:/usr/local/fledge/lib
            storageExec=${FLEDGE_ROOT}/services/fledge.services.storage
        else
            storageExec=${FLEDGE_ROOT}/services/storage
        fi
        write_log "" "scripts.services.storage" "info" "Fledge storage microservice found in FLEDGE_ROOT location: ${FLEDGE_ROOT}" "logonly" ""
    fi
fi

# Call plugin start: this will create database if not set yet
${pluginStartScript} start ${FLEDGE_SCHEMA} ${managedEngine}

# Run storage service
${storageExec} "$@"
exit 0
