-- NOTE -once you are up with fledge_schema=34, Downgrade is NOT possible as we removed C-source binaries.
--       There is no way to get these back with current support.
-- See scripts/package/debian/upgrade/1.8.sh
