name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: ["bug"]
assignees: Mark Riddoch
body:
  - type: markdown
    attributes:
      value: |        
        ### Please read, before you post!

        This is a **BUG REPORT for issues in the existing code**.

        If you have general questions, code handling problems, or ideas, please use the:

        - Discussion-board: https://github.com/fledge-iot/fledge/discussions
        - Slack-Channel: Use the fledge or fledge-help Slack Channel on https://slack.lfedge.org

        Verify first that your issue is not already reported on https://github.com/fledge-iot/fledge/issues

        ---
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: "Environment Platform"
      description: Please enter the environment details
      placeholder: Information about the system or platform (e.g., OS, version, architecture).
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Fledge Version"
      description: Please enter the version details
      placeholder: The specific version of fledge you are using.
    validations:
      required: true
  - type: dropdown
    id: installation-method
    attributes:
      label: "Installation"
      description: Fledge installation via
      options:
        - Source Code
        - Package based
        - Docker Container
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Steps To Reproduce"
      description: Please enter an explicit description of your issue
      value: |
        1. 
        2. 
        3. 
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: "Expected Behavior"
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log (i.e syslogs) output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: textarea
    id: support-bundle
    attributes:
      label: "Support bundle"
      description: Please share the support bundle. It would be highly appreciated, as it is essential for further troubleshooting.
      placeholder: Use the Fledge GUI interface to collect the support bundle. Navigate to the left menu, select the 'Support' menu item, click on 'Request New,' and then download the bundle.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        #### Thank you for taking the time to file a bug report! Your bug request will be reviewed by the team.
