name: "📝 Report a documentation issue"
description: "Is something wrong, confusing or missing in the docs?"
labels: ["documentation"]
assignees: Mark Riddoch
body:
  - type: input
    id: version
    attributes:
      label: "Version"
      description: Please enter the version from https://fledge-iot.readthedocs.io
      placeholder: Obtain information about the version (e.g., latest, nightly)
    validations:
      required: true
  - type: textarea
    id: describe-issue
    attributes:
      label: "Describe the documentation issue"
    validations:
      required: true
  - type: textarea
    id: what-solution
    attributes:
      label: "What solution would you like to see?"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        #### Thank you for taking the time to file a docs issue report! Your request will be reviewed by the team.
