#!/usr/bin/env bash


echo "Stopping Fledge"
export FLEDGE_ROOT=$1

cd ${1}/scripts/ && ./fledge stop

echo 'resetting fledge'
echo -e "YES\nYES" | ./fledge reset || exit 1
echo
echo "Starting Fledge"
./fledge start
echo "Fledge Status"
./fledge status
