#!/usr/bin/env bash

./check_env
[[ $? -eq 0 ]]  || exit 1

cat /etc/os-release | grep PRETTY_NAME | cut -f2 -d"="
uname -a

sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
sudo sed -i "/\b\(archives.fledge-iot.org\)\b/d" /etc/apt/sources.list
sudo rm -f /etc/apt/sources.list.d/fledge.list;


export DEBIAN_FRONTEND=noninteractive

sudo apt update && sudo apt upgrade -y && sudo apt update
echo "==================== DONE update, upgrade, update ============================"

echo "==================== INSTALLING jq =================="
sudo apt install -y jq
echo "==================== DONE =================="

BUILD_VERSION="nightly"
if [[ $# -gt 0 ]]
 then
 BUILD_VERSION=$1
fi

VERSION_CODENAME=$(cat /etc/os-release | grep VERSION_CODENAME | cut -f2 -d"=")

wget -q -O - http://archives.fledge-iot.org/KEY.gpg | sudo apt-key add -
echo "deb http://archives.fledge-iot.org/${BUILD_VERSION}/${VERSION_CODENAME}/$(arch)/ /" | sudo tee -a /etc/apt/sources.list
sudo apt update

time sudo -E apt install -yq fledge
echo "==================== DONE INSTALLING Fledge =================="

time sudo apt install -y fledge-gui
echo "==================== DONE INSTALLING Fledge GUI ======================"

time sudo apt install -y fledge-service-notification fledge-filter-expression fledge-filter-python35 fledge-filter-rms \
fledge-filter-fft fledge-filter-delta fledge-filter-metadata fledge-filter-change \
fledge-notify-asset fledge-notify-python35 fledge-notify-email \
fledge-rule-simple-expression fledge-rule-average \
fledge-north-httpc \
fledge-south-sinusoid fledge-south-rpienviro fledge-south-randomwalk fledge-south-game fledge-south-modbus fledge-south-http-south
echo "==================== DONE INSTALLING PLUGINS =================="
