#!/usr/bin/env bash

ITERATIONS=100
./remove
./install 1.7.0RC

for i in $(seq ${ITERATIONS}); do
	echo "***************"
	echo "***************"
	echo "Run $i"
	echo "***************"
	echo "***************"
	./reset
	./test || break
done

