#!/usr/bin/env bash

time sudo apt purge -y fledge fledge-gui
# If running on docker, do not remove as Docker volume is 
# mounted at /usr/local/fledge/data
if [ "${FLEDGE_ENVIRONMENT}" != "docker" ]; then     
    sudo rm -rf /usr/local/fledge
fi