#!/usr/bin/env bash

echo "Stopping Fledge using systemctl ..."
sudo systemctl stop fledge
echo "YES" | /usr/local/fledge/bin/fledge reset || exit 1
echo
echo "Starting Fledge using systemctl ..."
sudo systemctl start fledge
echo "Fledge Status"
sudo systemctl status fledge | grep "Active"