#!/usr/bin/env bash
set -e

__author__="Ashish Jabble"
__copyright__="Copyright (c) 2019 Dianomic Systems Inc."
__license__="Apache 2.0"
__version__="1.0.0"

######################################################################################################
# Usage text for this script
# $FLEDGE_ROOT/tests/system/python/scripts/package/setup ${PACKAGE_BUILD_VERSION}
######################################################################################################

PACKAGE_BUILD_VERSION=$1

[[ -z "${PACKAGE_BUILD_VERSION}" ]] && echo "Build Version not found." && exit 1

ID=$(cat /etc/os-release | grep -w ID | cut -f2 -d"=")
UNAME=`uname -m`
VERSION_ID=$(cat /etc/os-release | grep -w VERSION_ID | cut -f2 -d"=" |  tr -d '"')
echo "version id is "${VERSION_ID}

if [[ ${ID} = "ubuntu" ]]; then
    VERSION_ID=$(echo "${VERSION_ID//.}")
    ID="ubuntu${VERSION_ID}";
elif [[ ${ID} = "raspbian" ]]; then
    ID=$(cat /etc/os-release | grep VERSION_CODENAME | cut -f2 -d"=")
    UNAME="armv7l"
fi

echo "Build version is "${PACKAGE_BUILD_VERSION}
echo "ID is "${ID}
echo "uname is "${UNAME}

sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
sudo sed -i "/\b\(archives.fledge-iot.org\)\b/d" /etc/apt/sources.list

sudo apt update && sudo apt upgrade -y && sudo apt update
echo "==================== DONE update, upgrade, update ============================"

wget -q -O - http://archives.fledge-iot.org/KEY.gpg | sudo apt-key add -
# FIXME: for centos/rhel
echo "deb http://archives.fledge-iot.org/${PACKAGE_BUILD_VERSION}/${ID}/${UNAME}/ /" | sudo tee -a /etc/apt/sources.list
sudo apt update

time sudo DEBIAN_FRONTEND=noninteractive apt install -yq fledge
echo "==================== DONE INSTALLING Fledge =================="

time sudo apt install -y fledge-gui
echo "==================== DONE INSTALLING Fledge GUI ======================"
