FLEDGE_URL="http://localhost:8081/fledge"
TEST_RUN_TIME=3600
PI_IP="localhost"
PI_USER="Administrator"
PI_PASSWORD="password"
READINGSRATE="100"   # It is the readings rate per second per service
PURGE_INTERVAL_SECONDS="180"
STORAGE='sqlite' # postgres, sqlite-in-memory, sqlitelb
READING_PLUGIN_DB='Use main plugin'