FLEDGE_URL="http://localhost:8081/fledge"
TEST_RUN_TIME=3600
PI_IP="localhost"
PI_USER="Administrator"
PI_PASSWORD="password"
READINGS_RATE="100"   # It is the readings rate per second per service
PURGE_INTERVAL_SECONDS="180"
STORAGE='sqlite' # postgres, sqlite-in-memory, sqlitelb
READING_PLUGIN_DB='Use main plugin'
MEMORY_THRESHOLD=20    # If system memory falls below the specified memory threshold percentage, Fledge halts and generates a support bundle with a Valgrind report.