#!/bin/bash

##--------------------------------------------------------------------
## Copyright (c) 2017 OSIsoft, LLC
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##--------------------------------------------------------------------

set -e

#
# This is the startup script for foglamp
#
USAGE="Usage: `basename ${0}` {help|start}"


# Check FOGLAMP_ROOT
if [ -z ${FOGLAMP_ROOT+x} ]; then
    FOGLAMP_ROOT="/usr/local/foglamp"
fi


## The Logging Handler
#
# Paramaters: $1 - Severity:
#                  - debug
#                  - info
#                  - notice
#                  - err
#                  - crit
#                  - alert
#                  - emerg
#             $2 - Message
#             $3 - Output:
#                  - logonly : send the message only to syslog
#                  - all     : send the message to syslog and stdout
#                  - outonly " send the message only to stdout
#             $4 - Format
#                - pretty : Do not show the date and priority
#
foglamp_log() {

    # Check log severity
    if ! [[ "$1" =~ ^(debug|info|notice|err|crit|alert|emerg)$ ]]; then
        foglamp_log "err" "Internal error: unrecognized priority: $1" $3
        exit 1
    fi

    # Log to syslog
    if [[ "$3" =~ ^(logonly|all)$ ]]; then
        logger -p local0.$1 -t foglamp.core $2
    fi

    # Log to Stdout
    if [[ "$3" =~ ^(outnly|all)$ ]]; then
        if [[ "$4" == "pretty" ]]; then
            echo "$2" >&2
        else
            echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
        fi
    fi

}


## FogLAMP Start
foglamp_start() {

    if ! [[ -x "$(command -v python3)" ]]; then
        foglamp_log "err" "Python interpreter not found, FogLAMP cannot start." "all" "pretty"
        exit 1
    fi

    PYTHONPATH=${FOGLAMP_ROOT}/python
    export PYTHONPATH
    if [[ -e "$PYTHONPATH/foglamp/services/core/__main__.py" ]]; then
        python3 -m foglamp.services.core > /dev/null 2>&1 & disown
        foglamp_log "info" "FogLAMP started." "all" "pretty"
    else
        foglamp_log "err" "FogLAMP core not found." "all" "pretty"
        exit 1
    fi

}


## FogLAMP Script Help
foglamp_help() {

    echo "${USAGE}
FogLAMP admin script
The script is used to start FogLAMP
Arguments:
 start   - Start FogLAMP core (core will start other services).
 help    - This text"

}


### Main Logic ###
case "$1" in
  start)
    foglamp_start
    ;;
  help)
    foglamp_help
    ;;
  *)
    echo "${USAGE}"
    exit 1
esac


exit $?
