#!/bin/bash

##--------------------------------------------------------------------
## Copyright (c) 2017-2018 OSIsoft, LLC
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##--------------------------------------------------------------------

#
# This script is used to call the PosegreSQL storage plugin script
# to store and retrieve the sensor data when the database
# is embedded in FogLAMP
#

#set -x

# Include common code
source "${FOGLAMP_ROOT}/scripts/common/get_storage_plugin.sh"

PLUGIN_TO_USE=""

# Logger wrapper
storage_log() {
    write_log "Storage" "script.storage" "$1" "$2" "$3" "$4"
}

#############
## MAIN LOGIC
#############

# Check if the storage cache file exists
if [[ -e "$FOGLAMP_DATA/etc/storage.json" ]]; then

    # Extract plugin
    PLUGIN_TO_USE=`get_plugin_from_storage "$FOGLAMP_DATA/etc/storage.json"`

    # Check if the plugin has been found
    if [[ "${#PLUGIN_TO_USE}" -eq 0 ]]; then
        storage_log "err" "Missing plugin in FogLAMP storage cache file storage.json" "all" "pretty"
    fi

fi

if [[ "${#PLUGIN_TO_USE}" -eq 0 ]]; then

    # Extract the default storage plugin from the configuration file
    PLUGIN_TO_USE=`get_default_storage_plugin "$FOGLAMP_DATA/etc/foglamp.json"`
    if [[ "${#PLUGIN_TO_USE}" -eq 0 ]]; then
        storage_log "err" "FogLAMP cannot start." "all" "pretty"
        storage_log "err" "Missing default plugin in FogLAMP configuration file foglamp.json" "all" "pretty"
        exit 1
    fi

fi

PLUGIN_SCRIPT="$FOGLAMP_ROOT/scripts/plugins/storage/$PLUGIN_TO_USE.sh"
if [[ ! -x "$PLUGIN_SCRIPT" ]]; then

    # Missing storage plugin script
    storage_log "err" "FogLAMP cannot start." "all" "pretty"
    storage_log "err" "Missing Storage Plugin script $PLUGIN_SCRIPT." "all" "pretty"
    exit 1

fi

# Pass action in $1 and FOGLAMP_VERSION in $2
source "$PLUGIN_SCRIPT" $1 $2

# exit cannot be used because the script is sourced.
#exit $?

