#!/bin/bash

declare FLEDGE_ROOT
declare FLEDGE_DATA
declare PYTHONPATH

# Run a Fledge task written in Python
if [ "${FLEDGE_ROOT}" = "" ]; then
	FLEDGE_ROOT=/usr/local/fledge
fi

if [ ! -d "${FLEDGE_ROOT}" ]; then
	logger "Fledge home directory missing or incorrectly set environment"
	exit 1
fi

if [ ! -d "${FLEDGE_ROOT}/python" ]; then
	logger "Fledge home directory is missing the Python installation"
	exit 1
fi

# Adds required paths for the execution of the python module if not already defined
if [ "${PYTHONPATH}" = "" ]; then

	export PYTHONPATH="${FLEDGE_ROOT}/python"
fi

export FLEDGE_DATA=$FLEDGE_ROOT/data

# Include common code
source "${FLEDGE_ROOT}/scripts/common/get_storage_plugin.sh"

# Evaluates which storage engine is enabled and it uses the proper command
storage=`get_storage_plugin`

if [ "${storage}" == "sqlite" ]; then

    python3 -m fledge.plugins.storage.sqlite.backup_restore.backup_sqlite "$@"

elif [ "${storage}" == "postgres" ]; then

    python3 -m fledge.plugins.storage.postgres.backup_restore.backup_postgres "$@"
else
    logger "ERROR: the backup functionality for the storage engine :${storage}: is not implemented."
    exit 1
fi




