#!/bin/bash

##--------------------------------------------------------------------
## Copyright (c) 2018 OSIsoft, LLC
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##--------------------------------------------------------------------


# @date: 2018-01-02
#
# Bash Script to check for expired certificates and repalce with temporary certificates

if [ -z ${FLEDGE_ROOT+x} ]; then
    # Set FLEDGE_ROOT as the default directory
    FLEDGE_ROOT="/usr/local/fledge"
    export FLEDGE_ROOT
fi

# Check if the default directory exists
if [[ ! -d "${FLEDGE_ROOT}" ]]; then
    logger -p local0.err -t "fledge.script.tasks.cjeck_certs" "Check_certs cannot be executed: ${FLEDGE_ROOT} is not a valid directory."
    echo "Fledge cannot be executed: ${FLEDGE_ROOT} is not a valid directory."
    echo "Create the enviroment variable FLEDGE_ROOT before using check_certs."
    echo "Specify the base directory for Fledge and set the variable with:"
    echo "export FLEDGE_ROOT=<basedir>"
    exit 1
fi

. $FLEDGE_ROOT/scripts/common/write_log.sh

if [ -z ${FLEDGE_DATA+x} ]; then
	export dir=$FLEDGE_ROOT/data/etc/certs
else
	export dir=$FLEDGE_DATA/etc/certs
fi

export day=`expr 60 \* 60 \* 24`
export week=`expr $day \* 7`
certs=`echo $dir/*.cert`
for cert in $certs
do
	openssl x509 -noout -checkend $day -in $cert >/dev/null
	if [ $? -eq 1 ]; then
			write_log "" "fledge.check_certs" "err" "Certificate $cert will expire in less than a day" "all" "pretty"
			cd $FLEDGE_ROOT
			scripts/certificates `basename $cert .cert` 7
	else
		openssl x509 -noout -checkend $week -in $cert >/dev/null
		if [ $? -eq 1 ]; then
			write_log "" "fledge.check_certs" "warn" "Certificate $cert will expire in less than a week" "all" "pretty"
		fi
	fi
done
