#!/bin/sh
# Run a FogLAMP task written in Python
if [ "${FOGLAMP_ROOT}" = "" ]; then
	FOGLAMP_ROOT=/usr/local/foglamp
fi

if [ ! -d "${FOGLAMP_ROOT}" ]; then
	logger "FogLAMP home directory missing or incorrectly set environment"
	exit 1
fi

if [ ! -d "${FOGLAMP_ROOT}/python" ]; then
	logger "FogLAMP home directory is missing the Python installation"
	exit 1
fi

# Adds required paths for the execution of the python module
if [ "${PYTHONPATH}" = "" ]; then
	export PYTHONPATH="$PYTHONPATH:${FOGLAMP_ROOT}/python"
fi

# Avoid FogLAMP termination at the FogLAMP stop
command="python3 -m foglamp.tasks.backup_restore.restore $@"
nohup $command </dev/null >/dev/null 2>&1 &
