#!/bin/bash

# Run a FogLAMP task written in Python
if [ "${FOGLAMP_ROOT}" = "" ]; then
	FOGLAMP_ROOT=/usr/local/foglamp
fi

if [ ! -d "${FOGLAMP_ROOT}" ]; then
	logger "FogLAMP home directory missing or incorrectly set environment"
	exit 1
fi

if [ ! -d "${FOGLAMP_ROOT}/python" ]; then
	logger "FogLAMP home directory is missing the Python installation"
	exit 1
fi

# Adds required paths for the execution of the python module if not already defined
if [ "${PYTHONPATH}" = "" ]; then

	export PYTHONPATH="${FOGLAMP_ROOT}/python"
fi

# Include common code
source "${FOGLAMP_ROOT}/scripts/common/get_storage_plugin.sh"

# Evaluates with storage is enabled and it uses the problems commands
storage=`get_storage_plugin`

if [ "${storage}" == "sqlite" ]; then

    command="python3 -m foglamp.plugins.storage.sqlite.backup_restore.restore_sqlite $@"
else
    command="python3 -m foglamp.plugins.storage.postgres.backup_restore.restore_postgres $@"
fi

# Avoid FogLAMP termination at the FogLAMP stop
nohup $command </dev/null >/dev/null 2>&1 &

