#!/usr/bin/env bash
# Run a Fledge south service written in Python
if [ "${FLEDGE_ROOT}" = "" ]; then
	FLEDGE_ROOT=/usr/local/fledge
fi

if [ ! -d "${FLEDGE_ROOT}" ]; then
	logger "Fledge home directory missing or incorrectly set environment"
	exit 1
fi

if [ ! -d "${FLEDGE_ROOT}/python" ]; then
	logger "Fledge home directory is missing the Python installation"
	exit 1
fi

# We run the Python code from the python directory
cd "${FLEDGE_ROOT}/python"

os_name=`(grep -o '^NAME=.*' /etc/os-release | cut -f2 -d\" | sed 's/"//g')`

if [[ $os_name == *"Raspbian"*  ]]; then

	cpulimit -l 40 -- python3 -m fledge.tasks.statistics "$@"
else
	# Standard execution on other platforms
	$FLEDGE_ROOT/tasks/statistics_history "$@"
fi
