#!/bin/sh
# Run a Fledge task written in C

# Bash Script to check for expired certificates and repalce with temporary certificates

if [ -z ${FLEDGE_ROOT+x} ]; then
    # Set FLEDGE_ROOT as the default directory
    FLEDGE_ROOT="/usr/local/fledge"
    export FLEDGE_ROOT
fi

# Check if the default directory exists
if [[ ! -d "${FLEDGE_ROOT}" ]]; then
    echo "Fledge cannot be executed: ${FLEDGE_ROOT} is not a valid directory."
    echo "Create the enviroment variable FLEDGE_ROOT before using check_certs."
    echo "Specify the base directory for Fledge and set the variable with:"
    echo "export FLEDGE_ROOT=<basedir>"
    exit 1
fi

. $FLEDGE_ROOT/scripts/common/write_log.sh


cd "${FLEDGE_ROOT}"

./tasks/update_alerts "$@"

