#!/usr/bin/env bash
set -e

__author__="Ashish Jabble"
__copyright__="Copyright (c) 2019 Dianomic Systems"
__license__="Apache 2.0"
__version__="1.0.0"

###########################################################################################################
# Usage text for this script
# $FLEDGE_ROOT/tests/system/python/scripts/install_python_plugin {BRANCH_NAME} {PLUGIN_TYPE} {PLUGIN_NAME}
###########################################################################################################

BRANCH_NAME=$1
PLUGIN_TYPE=$2
PLUGIN_NAME=$3
USE_PIP_CACHE=$4

[[ -z "${BRANCH_NAME}" ]] && echo "Branch name not found." && exit 1
[[ -z "${PLUGIN_TYPE}" ]] && echo "Plugin type not found." && exit 1
[[ -z "${PLUGIN_NAME}" ]] && echo "Plugin name not found." && exit 1

USE_PIP_CACHE=${USE_PIP_CACHE,,}
if [[ "${USE_PIP_CACHE}" = false ]]; then USE_PIP_CACHE="--no-cache-dir"; else USE_PIP_CACHE=""; fi


REPO_NAME=fledge-${PLUGIN_TYPE}-${PLUGIN_NAME}

if [ "${PLUGIN_NAME}" == "http_south" ] || [ "${PLUGIN_NAME}" == "http_north" ] ; then
   REPO_NAME=fledge-${PLUGIN_TYPE}-http
fi


clean () {
   rm -rf /tmp/${REPO_NAME}
   rm -rf ${FLEDGE_ROOT}/python/fledge/plugins/${PLUGIN_TYPE}/fledge-${PLUGIN_TYPE}-${PLUGIN_NAME}
}

clone_repo () {
   git clone -b ${BRANCH_NAME} --single-branch https://github.com/fledge-iot/${REPO_NAME}.git /tmp/${REPO_NAME}
}

copy_file_and_requirement () {
    if [ "$PLUGIN_NAME" = "http" ]; then
        cp -r /tmp/${REPO_NAME}/python/fledge/plugins/${PLUGIN_TYPE}/${PLUGIN_NAME}_${PLUGIN_TYPE} $FLEDGE_ROOT/python/fledge/plugins/${PLUGIN_TYPE}/
    else
        cp -r /tmp/${REPO_NAME}/python/fledge/plugins/${PLUGIN_TYPE}/${PLUGIN_NAME} $FLEDGE_ROOT/python/fledge/plugins/${PLUGIN_TYPE}/
    fi
    req_file=$(find /tmp/${REPO_NAME} -name requirement*.txt)
    [ ! -z "${req_file}" ] && python3 -m pip install --user -Ir ${req_file} ${USE_PIP_CACHE} || echo "No such external dependency needed for ${PLUGIN_NAME} plugin."
}

clean
clone_repo
copy_file_and_requirement
echo "${PLUGIN_NAME} plugin is installed."
