#!/usr/bin/env bash
set -e

__author__="Ashish Jabble"
__copyright__="Copyright (c) 2019 Dianomic Systems"
__license__="Apache 2.0"
__version__="1.0.0"

######################################################################################################
# Usage text for this script
# $FLEDGE_ROOT/tests/system/python/scripts/install_c_plugin {BRANCH_NAME} {PLUGIN_TYPE} {PLUGIN_NAME}
######################################################################################################

BRANCH_NAME=$1
PLUGIN_TYPE=$2
PLUGIN_NAME=$3

[[ -z "${BRANCH_NAME}" ]] && echo "Branch name not found." && exit 1
[[ -z "${PLUGIN_TYPE}" ]] && echo "Plugin type not found." && exit 1
[[ -z "${PLUGIN_NAME}" ]] && echo "Plugin name not found." && exit 1

os_name=`(grep -o '^NAME=.*' /etc/os-release | cut -f2 -d\" | sed 's/"//g')`
REPO_NAME=fledge-${PLUGIN_TYPE}-${PLUGIN_NAME,,}
if [[ "${PLUGIN_TYPE}" = "rule" ]]; then rm -rf /tmp/fledge-service-notification; fi


clean () {
   rm -rf /tmp/${REPO_NAME}
   rm -rf ${FLEDGE_ROOT}/plugins/${PLUGIN_TYPE}/${PLUGIN_NAME}
}

clone_repo () {
   git clone -b ${BRANCH_NAME} --single-branch https://github.com/fledge-iot/${REPO_NAME}.git /tmp/${REPO_NAME}
}

install_requirement (){
    req_file=$(find /tmp/${REPO_NAME} -name requirement*.sh)
    [[ ! -z "${req_file}" ]] && ${req_file} || echo "No external dependency needed for ${PLUGIN_NAME} plugin."
}

install_binary_file () {
   if [[ "${PLUGIN_TYPE}" = "rule" ]]
   then
        # fledge-service-notification repo is required to build notificationRule Plugins
        service_repo_name='fledge-service-notification'
        git clone -b ${BRANCH_NAME} --single-branch https://github.com/fledge-iot/${service_repo_name}.git /tmp/${service_repo_name}
        export NOTIFICATION_SERVICE_INCLUDE_DIRS=/tmp/${service_repo_name}/C/services/common/include
   fi
   
   if [ -f /tmp/${REPO_NAME}/build.sh ]; then
	cd /tmp/${REPO_NAME}; ./build.sh -DFLEDGE_INSTALL=${FLEDGE_ROOT}; cd build && make install;
   else
        if [[ $os_name == *"Red Hat"* || $os_name == *"CentOS"* ]]; then    
            set +e
            source scl_source enable rh-postgresql13
            source scl_source enable devtoolset-7
            set -e
        fi
        mkdir -p /tmp/${REPO_NAME}/build; cd /tmp/${REPO_NAME}/build; cmake -DFLEDGE_INSTALL=${FLEDGE_ROOT} ..; make -j4 && make install; cd -
   fi   
   
}

clean
clone_repo
install_requirement
install_binary_file
echo "${PLUGIN_NAME} plugin is installed."
