#!/usr/bin/env bash
set -e

__author__="Ashish Jabble"
__copyright__="Copyright (c) 2019 Dianomic Systems"
__license__="Apache 2.0"
__version__="1.0.0"

##########################################################################################
# Usage text for this script
# $FLEDGE_ROOT/tests/system/python/scripts/install_c_service {BRANCH_NAME} {SERVICE_NAME}
##########################################################################################

BRANCH_NAME=$1
SERVICE_NAME=$2

[[ -z "${BRANCH_NAME}" ]] && echo "Branch name not found." && exit 1
[[ -z "${SERVICE_NAME}" ]] && echo "Service name not found." && exit 1

os_name=`(grep -o '^NAME=.*' /etc/os-release | cut -f2 -d\" | sed 's/"//g')`
REPO_NAME=fledge-service-${SERVICE_NAME}

clean () {
   rm -rf /tmp/${REPO_NAME}
   rm -rf ${FLEDGE_ROOT}/services/fledge.services.${SERVICE_NAME}
}

clone_repo () {
   git clone -b ${BRANCH_NAME} --single-branch https://github.com/fledge-iot/${REPO_NAME}.git /tmp/${REPO_NAME}
}

install_binary_file () {
   
   if [ -f /tmp/${REPO_NAME}/build.sh ]; then
	cd /tmp/${REPO_NAME}; ./build.sh -DFLEDGE_INSTALL=${FLEDGE_ROOT}; cd build && make install;
   else
        if [[ $os_name == *"Red Hat"* || $os_name == *"CentOS"* ]]; then    
            set +e
            source scl_source enable rh-postgresql13
            source scl_source enable devtoolset-7
            set -e
        fi
        mkdir -p /tmp/${REPO_NAME}/build; cd /tmp/${REPO_NAME}/build; cmake -DFLEDGE_INSTALL=${FLEDGE_ROOT} ..; make -j4 && make install; cd -
   fi   
   
}

clean
clone_repo
install_binary_file
echo "${SERVICE_NAME} service is installed."
