#!/usr/bin/env bash
set -e

__author__="Vaibhav Singhal"
__copyright__="Copyright (c) 2019 Dianomic Systems"
__license__="Apache 2.0"
__version__="1.0.0"

###########################################################################################################
# Usage text for this script
# $FOGLAMP_ROOT/tests/system/python/scripts/install_python_plugin {BRANCH_NAME} {PLUGIN_TYPE} {PLUGIN_NAME}
# {REMOTE_USER} {REMOTE_IP} {AUTH_KEY} {FOGLAMP_ROOT}
###########################################################################################################

BRANCH_NAME=$1
PLUGIN_TYPE=$2
PLUGIN_NAME=$3
USE_PIP_CACHE=$4
REMOTE_USER=$5
REMOTE_IP=$6
AUTH_KEY=$7
FOGLAMP_ROOT=$8

[[ -z "${BRANCH_NAME}" ]] && echo "Branch name not found." && exit 1
[[ -z "${PLUGIN_TYPE}" ]] && echo "Plugin type not found." && exit 1
[[ -z "${PLUGIN_NAME}" ]] && echo "Plugin name not found." && exit 1

USE_PIP_CACHE=${USE_PIP_CACHE,,}
if [[ "${USE_PIP_CACHE}" = false ]]; then USE_PIP_CACHE="--no-cache-dir"; else USE_PIP_CACHE=""; fi


REPO_NAME=foglamp-${PLUGIN_TYPE}-${PLUGIN_NAME}

if [ "${PLUGIN_NAME}" == "http_south" ] || [ "${PLUGIN_NAME}" == "http_north" ] ; then
   REPO_NAME=foglamp-${PLUGIN_TYPE}-http
fi


clean () {
   ssh -i ${AUTH_KEY} ${REMOTE_USER}@${REMOTE_IP} "rm -rf /tmp/${REPO_NAME}"
   ssh -i ${AUTH_KEY} ${REMOTE_USER}@${REMOTE_IP} "rm -rf ${FOGLAMP_ROOT}/python/foglamp/plugins/${PLUGIN_TYPE}/foglamp-${PLUGIN_TYPE}-${PLUGIN_NAME}"
}

clone_repo () {
   ssh -i ${AUTH_KEY} ${REMOTE_USER}@${REMOTE_IP} "git clone -b ${BRANCH_NAME} --single-branch https://github.com/foglamp/${REPO_NAME}.git /tmp/${REPO_NAME}"
}

copy_file_and_requirement () {
    if [ "$PLUGIN_NAME" = "http" ]; then
        ssh -i ${AUTH_KEY} ${REMOTE_USER}@${REMOTE_IP} "cp -r /tmp/${REPO_NAME}/python/foglamp/plugins/${PLUGIN_TYPE}/${PLUGIN_NAME}_south $FOGLAMP_ROOT/python/foglamp/plugins/${PLUGIN_TYPE}/"
    else
        ssh -i ${AUTH_KEY} ${REMOTE_USER}@${REMOTE_IP} "cp -r /tmp/${REPO_NAME}/python/foglamp/plugins/${PLUGIN_TYPE}/${PLUGIN_NAME} $FOGLAMP_ROOT/python/foglamp/plugins/${PLUGIN_TYPE}/"
    fi
    req_file=$(ssh -i ${AUTH_KEY} ${REMOTE_USER}@${REMOTE_IP} find /tmp/${REPO_NAME} -name requirement*.txt)
    [ ! -z "${req_file}" ] && ssh -i ${AUTH_KEY} ${REMOTE_USER}@${REMOTE_IP} pip3 install --user -Ir ${req_file} ${USE_PIP_CACHE} || echo "No such external dependency needed for ${PLUGIN_NAME} plugin."
}

clean
clone_repo
copy_file_and_requirement
echo "${PLUGIN_NAME} plugin is installed."
