#!/usr/bin/env bash
set -e

__author__="Ashish Jabble"
__copyright__="Copyright (c) 2019 Dianomic Systems"
__license__="Apache 2.0"
__version__="1.0.0"

#########################################################
# Usage text for this script
# $FLEDGE_ROOT/tests/system/python/scripts/reset_plugins
#########################################################

remove_south () {
    rm -rf $FLEDGE_ROOT/plugins/south
    path="$FLEDGE_ROOT/python/fledge/plugins/south"
    find ${path} -maxdepth 1 | grep -v "^${path}$" | egrep -v '(__init__.py)' | xargs rm -rf
}

remove_north () {
    path="$FLEDGE_ROOT/plugins/north"
    find ${path} -maxdepth 1 | grep -v "^${path}$" | egrep -v '(OMF)' | xargs rm -rf
    path="$FLEDGE_ROOT/python/fledge/plugins/north"
    find ${path} -maxdepth 1 | grep -v "^${path}$" | egrep -v '(common|empty|README.rst|__init__.py)' | xargs rm -rf
}

remove_filter () {
    path="$FLEDGE_ROOT/plugins/filter"
    find ${path} -maxdepth 1 | grep -v "^${path}$" | egrep -v '(common)' | xargs rm -rf
    path="$FLEDGE_ROOT/python/fledge/plugins/filter"
    find ${path} -maxdepth 1 | grep -v "^${path}$" | egrep -v '(__init__.py)' | xargs rm -rf
}

remove_notification_delivery () {
    rm -rf $FLEDGE_ROOT/plugins/notificationDelivery
    rm -rf $FLEDGE_ROOT/python/fledge/plugins/notificationDelivery
}

remove_notification_rule () {
    rm -rf $FLEDGE_ROOT/plugins/notificationRule
    rm -rf $FLEDGE_ROOT/python/fledge/plugins/notificationRule
}

remove_all () {
    remove_south
    remove_north
    remove_filter
    remove_notification_delivery
    remove_notification_rule
}

remove_all
echo "Removed all plugins..."