#!/usr/bin/env bash
set -e

__author__="Ashish Jabble"
__copyright__="Copyright (c) 2019 Dianomic Systems Inc."
__license__="Apache 2.0"
__version__="1.0.0"

######################################################################################################
# Usage text for this script
# $FOGLAMP_ROOT/tests/system/python/scripts/setup_package ${BUILD_VERSION}
######################################################################################################

BUILD_VERSION=$1

[[ -z "${BUILD_VERSION}" ]] && echo "Build Version not found." && exit 1

CODENAME=`lsb_release --codename | cut -f2`
UNAME=`uname -m`
RELEASE_VERSION=`lsb_release --release | cut -f2`

echo "Build version is "${BUILD_VERSION}
echo "Code name is "${CODENAME}
echo "uname is "${UNAME}
echo "Release version is "${RELEASE_VERSION}

if [[ ${CODENAME} = "xenial" && ${RELEASE_VERSION} = "16.04" ]]; then
    CODENAME="ubuntu1604";
elif [[ ${CODENAME} = "xenial" && ${RELEASE_VERSION} = "18.04" ]]; then
    CODENAME="ubuntu1804";
fi
echo "Final Code name is "${CODENAME}

sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
sudo sed -i "/\b\(archives.dianomic.com\)\b/d" /etc/apt/sources.list

sudo apt update && sudo apt upgrade -y && sudo apt update
echo "==================== DONE update, upgrade, update ============================"

wget -q -O - http://archives.dianomic.com/KEY.gpg | sudo apt-key add -
echo "deb http://archives.dianomic.com/${BUILD_VERSION}/${CODENAME}/${UNAME}/ /" | sudo tee -a /etc/apt/sources.list
sudo apt update

time sudo apt install -y foglamp
echo "==================== DONE INSTALLING FogLAMP =================="

time sudo apt install -y foglamp-gui
echo "==================== DONE INSTALLING FogLAMP GUI ======================"
